### ISSUE TITLE
2-1 주차

### ISSUE THREAD

**Issue by bnh5992** [IMS-STUDY/Spring-Boot-Study#5]
이론 : ORM, Repository 사용법 ex)findby , Spring JPA, 영속성 컨텍스트 조사
실습 : 본인의 간단한 서비스  데이터베이스 설계 및 생성
ex) 재고 시스템 database 구성 : 상품명, 가격, 납품업체, 수량 등으로 구성

**Comment by edgarlee1** [comment]
https://www.notion.so/3-65d3c50681f949e3af1ce93690e7ecd2?pvs=4

**Comment by YUUHWAH** [comment]
https://www.notion.so/7-9-c2c3eefd5f994075a40d1a19878e939f?pvs=4

**Comment by LikeHuTaoCoder** [comment]
https://fork-stick-091.notion.site/2-1-9064a32cb73f40cbb1ff6936e1755faf?pvs=4

**Comment by sojung102** [comment]
https://habitual-fairy-e40.notion.site/2-1-f8e68f7049804f34bb5bc5c50e64b065?pvs=4

**Comment by bluewing0303** [comment]
https://velog.io/@bluewing0303/%EB%B0%B1%EC%97%94%EB%93%9C-2-1-%EA%B3%BC%EC%A0%9C

**Comment by Potato-Iced** [comment]
https://icedpotato.notion.site/3-ORM-Spring-JPA-Repository-87a493e55ece43b39525040ba9c5e2b8?pvs=74
